#!/usr/bin/env bash
set -eo pipefail; [[ $CREW_TRACE ]] && set -x
source "$(dirname $0)/../common/functions"

PLUGIN_DIR="$(dirname $0)"

case "$1" in
  events)
    if [[ -f $CREW_EVENTS_LOGFILE ]] ; then
      if [[ $2 == "-t" ]]; then
        tail -f $CREW_EVENTS_LOGFILE
      else
        tail -n 100 $CREW_EVENTS_LOGFILE
      fi
    fi
    ;;

  events:on)
    echo "Enabling crew events logger"
    [[ -d $CREW_ROOT/.crewrc ]] || mkdir -p $CREW_ROOT/.crewrc
    echo "export CREW_EVENTS=1" > $CREW_ROOT/.crewrc/CREW_EVENTS
    ;;

  events:off)
    echo "Disabling crew events logger"
    rm -f $CREW_ROOT/.crewrc/CREW_EVENTS
    ;;

  events:list)
    if [[ "$CREW_EVENTS" ]]; then
      logged="$(find $PLUGIN_DIR -type l -printf '%f ' | sort)"
      crew_col_log_info2_quiet "Events currently logged"
      for hook in $logged ; do
        crew_col_log_msg "$hook"
      done
    else
      crew_log_warn "Events logger disabled"
    fi
    ;;

  help | events:help)
    cat && cat<<EOF
    events [-t], Show the last events (-t follows)
    events:list, List logged events
    events:on, Enable events logger
    events:off, Disable events logger
EOF
    ;;

  *)
    exit $CREW_NOT_IMPLEMENTED_EXIT
    ;;

esac

