#!/usr/bin/env bash
set -eo pipefail; [[ $CREW_TRACE ]] && set -x
source "$(dirname $0)/../common/functions"

CREW_RSYSLOG_FILTER=/etc/rsyslog.d/99-crew.conf
CREW_LOGROTATE_FILE=/etc/logrotate.d/crew

flag_rsyslog_needs_restart=n

# This can be done unconditionally as mkdir -p
# exits gracefully if the path already exists
mkdir -m 775 -p "$CREW_LOGS_DIR"
chown syslog:crew "$CREW_LOGS_DIR"

if [[ ! -f  "$CREW_EVENTS_LOGFILE" ]]; then
  touch "$CREW_EVENTS_LOGFILE"
  # chown syslog:root might not work on SUSE
  chown syslog:crew "$CREW_EVENTS_LOGFILE"
  chmod 664 "$CREW_EVENTS_LOGFILE"
fi

if [[ ! -f  "$CREW_RSYSLOG_FILTER" ]]; then
  cat >"$CREW_RSYSLOG_FILTER" <<EOF
:syslogtag, contains, "crew" $CREW_EVENTS_LOGFILE
EOF
  flag_rsyslog_needs_restart=y
fi

if [[ ! -f "$CREW_LOGROTATE_FILE" ]]; then
  cat >"$CREW_LOGROTATE_FILE" <<EOF
$CREW_LOGS_DIR/*.log {
        daily
        rotate 7
        missingok
        notifempty
        su syslog crew
        compress
        delaycompress
        postrotate
                reload rsyslog >/dev/null 2>&1 || true
        endscript
        create 664 syslog crew
}
EOF
  flag_rsyslog_needs_restart=y
fi

if [[ "$flag_rsyslog_needs_restart" == "y" ]]; then
  service rsyslog restart
fi

[[ ! "$CREW_EVENTS" ]] || crew_log_pluginhook_call "$(basename $0)" "$@"

exit 0
