#!/usr/bin/env bash
set -eo pipefail; [[ $CREW_TRACE ]] && set -x
source "$(dirname $0)/../common/functions"

STDIN=$(cat); APP="$1"; IMAGE="crew/$APP"
DOCKERFILE_ENV_FILE="$CREW_ROOT/$APP/DOCKERFILE_ENV_FILE"

> "$DOCKERFILE_ENV_FILE"
[[ -f "$CREW_ROOT/ENV" ]] && sed -e "s:^export ::g" -e "s:=':=:g" -e "s:'$::g" "$CREW_ROOT/ENV" > "$DOCKERFILE_ENV_FILE"
[[ -f "$CREW_ROOT/$APP/ENV" ]] && sed -e "s:^export ::g" -e "s:=':=:g" -e "s:'$::g" "$CREW_ROOT/$APP/ENV" >> "$DOCKERFILE_ENV_FILE"

echo "$STDIN --env-file=$DOCKERFILE_ENV_FILE"
