#!/bin/sh -e

. /usr/share/debconf/confmodule

readonly ACTION="${1:-configure}"
readonly VERSION="${2:-dev}"

db_input "high" "crew/web_config" || true
db_go || true

db_get "crew/web_config"
if [ $RET = "true" ]; then
    exit 0
fi

db_input "high" "crew/hostname" || true
db_input "high" "crew/vhost_enable" || true
if [ "$ACTION" != "reconfigure" ]; then
  db_input "high" "crew/key_file" || true
fi
db_go || true
