#!/bin/sh
set -e

. /usr/share/debconf/confmodule

readonly CREW_ROOT="${CREW_ROOT:-/home/crew}"

case "$1" in
  abort-upgrade|abort-remove|abort-deconfigure)
    ;;

  configure)
    mandb
    [ ! -x /usr/bin/docker.io ] || ln -sf /usr/bin/docker.io /usr/local/bin/docker
    modprobe aufs || echo "WARNING: Restart server to finish installing crew!"
    sshcommand create crew /usr/local/bin/crew
    egrep -i "^docker" /etc/group || groupadd docker
    usermod -aG docker crew
    crew plugins-install
    rm -f /home/crew/VERSION
    cp /var/lib/crew/STABLE_VERSION /home/crew/VERSION

    if [ -f /etc/init/crew-installer.conf ] && service crew-installer status 2> /dev/null | grep waiting; then
        sudo service crew-installer start
    fi

    db_get "crew/web_config"
    if [ "$RET" = "true" ]; then
      exit 0
    fi

    db_get "crew/vhost_enable"
    if [ "$RET" = "true" ]; then
        db_get "crew/hostname" 
        echo "$RET" > "${CREW_ROOT}/VHOST"
    else
        rm -f "${CREW_ROOT}/VHOST"
    fi

    db_get "crew/hostname"
    echo "$RET" > "${CREW_ROOT}/HOSTNAME"

    if [ -z "${DEBCONF_RECONFIGURE}" ]; then
      db_get "crew/key_file"
      sshcommand acl-add crew default < "$RET"
    fi
    ;;

  *)
    echo "postinst called with unknown argument \`$1'" >&2
    exit 1
    ;;
esac

exit 0
