#!/usr/bin/env bash
set -eo pipefail; [[ $CREW_TRACE ]] && set -x
source "$(dirname $0)/../common/functions"

case "$1" in
  apps)
    crew_log_info2_quiet "My Apps"
    find $CREW_ROOT -follow -maxdepth 1 -type d  \( ! -iname ".*" \)  -not -path $CREW_ROOT/tls | sed 's|^\./||g' | sed 's|'$CREW_ROOT'\/||' | tail -n +2 | sort
    ;;

  apps:create)
    [[ -z $2 ]] && echo "Please specify an app to run the command on" && exit 1
    [[ -d "$CREW_ROOT/$2" ]] && crew_log_warn "Name is already taken" && exit 1
    APP="$2"

    mkdir -p "$CREW_ROOT/$APP"
    echo "Creating $APP... done"
    ;;

  apps:destroy)
    [[ -z $2 ]] && echo "Please specify an app to run the command on" && exit 1
    verify_app_name "$2"
    [[ "$2" == "tls" ]] && echo "Unable to destroy tls directory" && exit 1
    APP="$2"; IMAGE="crew/$APP"

    [[ "$3" == "force" ]] && CREW_APPS_FORCE_DELETE=1
    if [[ -z "$CREW_APPS_FORCE_DELETE" ]]; then
      crew_log_warn "WARNING: Potentially Destructive Action"
      crew_log_warn "This command will destroy $APP (including all add-ons)."
      crew_log_warn "To proceed, type \"$APP\""
      echo ""

      read -p "> " app_name
      if [[ "$app_name" != "$APP" ]]; then
        crew_log_warn "Confirmation did not match $APP. Aborted."
        exit 1
      fi
    fi

    echo "Destroying $APP (including all add-ons)"

    pluginhook pre-delete $APP
    CREW_APP_CIDS=$(get_app_container_ids $APP)
    if [[ -n $CREW_APP_CIDS ]]; then
      for ID in $CREW_APP_CIDS;do
        docker stop $ID > /dev/null || true
        docker rm $ID  > /dev/null || true
      done
    fi

    docker images | grep $IMAGE | awk '{print $3}' | xargs docker rmi &> /dev/null &

    pluginhook post-delete $APP
    ;;

  help | apps:help)
    cat && cat<<EOF
    apps                                                       List your apps
    apps:create <app>                                          Create a new app
    apps:destroy <app>                                         Permanently destroy an app
EOF
    ;;

  *)
    exit $CREW_NOT_IMPLEMENTED_EXIT
    ;;

esac
